services:
  - type: web
    name: trpc-websockets
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - fromGroup: trpc-websockets
