services:
  - type: web
    name: trpc-websockets
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    healthCheckPath: /api/trpc/healthcheck
    envVars:
      - key: NODE_ENV
        value: production

      - fromGroup: trpc-websockets
