import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect, useRef, useLayoutEffect } from "react";
import { flushSync } from "react-dom";
import { trpc } from "../../utils/trpc";

const NotepadPage: NextPage = () => {
  const [message, setMessage] = useState("");
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [selection, setSelection] = useState({ start: 0, end: 0 });

  const addMessage = trpc.message.add.useMutation();
  const { status, data } = trpc.message.getText.useQuery();

  useEffect(() => {
    if (status === "success" && data) {
      setMessage(data);
    }
  }, [status, data]);

  // useLayoutEffect(() => {
  //   if (inputRef.current) {

  //   }
  // }, [selection.start, selection.end]);

  trpc.message.onAdd.useSubscription(undefined, {
    onData(newMessage) {
      console.log("message is ", message);
      if (newMessage) {
        setMessage(newMessage);
      }
      // inputRef?.current?.setSelectionRange(selection.start, selection.end);
    },
    onError(err) {
      console.error("Subscription error:", err);
    },
  });

  async function handleInput(e: React.ChangeEvent<HTMLTextAreaElement>) {
    const selectionStart = e.target.selectionStart;
    const character = e.target.value[e.target.selectionStart - 1];

    if (!character) return;

    const input = {
      position: selectionStart - 1,
      character: character,
    };

    try {
      await addMessage.mutateAsync(input);
    } catch {}

    console.log("Selection start: ");
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-start gap-10 p-4">
        <h1 className="text-4xl font-extrabold leading-normal text-neutral-100 md:text-[5rem]">
          Phantom <span className="text-rose-500">Notepad</span>
        </h1>
        <div className="flex w-full justify-center gap-2 lg:w-1/2">
          <textarea
            ref={inputRef}
            className="h-[550px] grow rounded p-5 "
            value={message}
            onChange={handleInput}
            onSelect={(e) => {
              setSelection({
                start: e.currentTarget.selectionStart || 0,
                end: e.currentTarget.selectionEnd || 0,
              });
            }}
            maxLength={1500}
          />
        </div>
      </main>
    </>
  );
};

export default NotepadPage;
